---
title: "Quantifying low-value care: a patient-centric versus service-centric lens"
author: "Kelsey Chalmers, Sallie-Anne Pearson, Adam G Elshaug"
date: 2017-10-01
categories: ["Papers"]
tags: ["research", "lowvaluecare"]
---

When creating the list of measured low-value services for The Lancet Overuse series, I wrote this article during my PhD about the ways to report and measure low-value care. 
[BMJ Quality and Safety](https://qualitysafety.bmj.com/content/26/10/855.abstract)

*Not open access, so please email me for a copy!*

> Low-value healthcare has been defined as care that is inappropriate for a specific clinical indication, inappropriate for a clinical indication in a specific population or an excessive frequency of services relative to expected benefit. Quantifying the prevalence of low-value healthcare informs clinicians and health policy makers on the use and associations of unwarranted care. In this Viewpoint, we clarify the approaches used in the literature for measuring and reporting the level of low-value care in a given population. Categorising low-value service measures depends on the denominator used. Future analyses should consider using all types of measures when possible, or explain why it is not practical or desirable to do so, and at the very least describe for the reader which measure has been used, as this can dramatically impact interpretation of the results.