---
title: "Developing indicators for measuring low-value care"
author: "Kelsey Chalmers, Tim Badgery-Parker, Sallie-Anne Pearson, Jonathan Brett, Ian A Scott, Adam G Elshaug"
date: 2018-12-01
categories: ["Papers"]
tags: ["research", "lowvaluecare"]
---

This was the first paper from my PhD thesis. 
[BMC Research Notes](https://bmcresnotes.biomedcentral.com/articles/10.1186/s13104-018-3270-4).

> Objective: Low-value health care refers to interventions where the risk of harm or costs exceeds the likely benefit for a patient. We aimed to develop indicators of low-value care, based on selected Choosing Wisely (CW) recommendations, applicable to routinely collected, hospital claims data.

> Results: We assessed 824 recommendations from the United States, Canada, Australia and the United Kingdom CW lists regarding their capacity to be measured in administrative hospital admissions datasets. We selected recommendations if they met the following criteria: the service occurred in the hospital setting (observable in setting); a claim recorded the use of the service (record of service); the appropriate/inappropriate use of the service could be mapped to information within the hospital claim (indication); and the service is consistently recorded in the claims (consistent documentation). We identified 17 recommendations (15 services) as measurable. We then developed low-value care indicators for two hospital datasets based on the selected recommendations, previously published indicators, and clinical input.

